FROM python:3.6-stretch
MAINTAINER Brian H. Grant <brian@hackoregon.org> & "M. Edward (Ed) Borasky <znmeb@znmeb.net>
ENV PYTHONUNBUFFERED 1

# Add Geo libraries
RUN mkdir /code
WORKDIR /code
RUN apt-get update && apt-get install -y \
  binutils \
  gdal-bin \
  libgeos-dev \
  libproj-dev \
  postgresql-client \
&& rm -rf /var/lib/apt/lists/*

COPY requirements/*.txt /code/
RUN pip install -r development.txt
RUN pip install -r geodjango.txt

RUN python
COPY . /code/
