# Generated by Django 2.0.1 on 2018-04-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JCHSData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapoint', models.CharField(help_text='Location of data', max_length=255)),
                ('source', models.CharField(help_text='Sheet of State of Housing Report appendix Excel file that this data comes from', max_length=4)),
                ('datatype', models.CharField(help_text='Description of the data this value represents', max_length=255)),
                ('valuetype', models.CharField(help_text='Type of data this value represents', max_length=255)),
                ('date', models.DateField(help_text='Date of this value, if representative of an entire year the value will be on Jan 1')),
                ('value', models.DecimalField(decimal_places=5, max_digits=24)),
            ],
        ),
    ]
