# Generated by Django 2.0.1 on 2018-04-18 20:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180418_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jchsdata',
            name='datapoint_clean',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='datapoint'),
        ),
        migrations.AlterField(
            model_name='jchsdata',
            name='datatype_clean',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='datatype'),
        ),
        migrations.AlterField(
            model_name='jchsdata',
            name='valuetype_clean',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='valuetype'),
        ),
    ]
