# Generated by Django 2.0.1 on 2018-05-01 05:49

import autoslug.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180418_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='HudHicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapoint', models.CharField(help_text='Location of data', max_length=255)),
                ('geography', models.CharField(help_text='Location type', max_length=255)),
                ('datatype', models.CharField(help_text='Description of the data this value represents', max_length=255)),
                ('shelter_status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='Type of shelter this value represents', max_length=255), size=None)),
                ('year', models.PositiveSmallIntegerField(help_text='Year of count')),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('datapoint_clean', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='datapoint')),
                ('datatype_clean', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='datatype')),
            ],
        ),
        migrations.CreateModel(
            name='HudPitData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapoint', models.CharField(help_text='Location of data', max_length=255)),
                ('geography', models.CharField(help_text='Location type', max_length=255)),
                ('datatype', models.CharField(help_text='Description of the data this value represents', max_length=255)),
                ('year', models.PositiveSmallIntegerField(help_text='Year of count')),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('datapoint_clean', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='datapoint')),
                ('datatype_clean', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='datatype')),
            ],
        ),
    ]
