# Generated by Django 2.0.1 on 2018-05-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hudhicdata_hudpitdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrbanInstituteRentalCrisisData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='Year of data')),
                ('eli_limit', models.DecimalField(decimal_places=2, help_text='HUD ELI limit for family of four in the county', max_digits=9)),
                ('county_fips', models.CharField(help_text='County FIPS code', max_length=10)),
                ('county_name', models.CharField(help_text='County name', max_length=255)),
                ('state_name', models.CharField(help_text='State name', max_length=255)),
                ('is_state_data', models.BooleanField()),
                ('eli_renters', models.DecimalField(decimal_places=2, help_text='Number of ELI renters in the county', max_digits=11)),
                ('aaa_units', models.DecimalField(decimal_places=2, help_text='Number of affordable, adequate, and available units in the county', max_digits=11)),
                ('noasst_units', models.DecimalField(decimal_places=2, help_text='Number of units paying less than 30% of income on rent and utilities, excluding units with project-based rental assistance', max_digits=11)),
                ('hud_units', models.DecimalField(decimal_places=2, help_text='Number of units subsidized by HUD rental assistance, excluding units that were affordable before assistance', max_digits=11)),
                ('usda_units', models.DecimalField(decimal_places=2, help_text='Number of units subsidized by USDA rental assistance. Imputed for 2000 data.', max_digits=11)),
                ('no_hud_units', models.DecimalField(decimal_places=2, help_text='Number of affordable, adequate, and available units without HUD rental assistance', max_digits=11)),
                ('no_usda_units', models.DecimalField(decimal_places=2, help_text='Number of affordable, adequate, and available units without USDA rental assistance', max_digits=11)),
            ],
        ),
    ]
