# Generated by Django 2.0.1 on 2018-05-17 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_urbaninstituterentalcrisisdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('policy_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('link1', models.CharField(max_length=255)),
                ('link1_name', models.CharField(max_length=255)),
                ('link2', models.CharField(max_length=255)),
                ('link2_name', models.CharField(max_length=255)),
                ('link3', models.CharField(max_length=255)),
                ('link3_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('government_entity', models.CharField(max_length=255)),
                ('year_implemented', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('link1', models.CharField(max_length=255)),
                ('link1_name', models.CharField(max_length=255)),
                ('link2', models.CharField(max_length=255)),
                ('link2_name', models.CharField(max_length=255)),
                ('link3', models.CharField(max_length=255)),
                ('link3_name', models.CharField(max_length=255)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Policy')),
            ],
        ),
    ]
