# Generated by Django 2.0.1 on 2018-05-23 23:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180517_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='category_clean',
            field=autoslug.fields.AutoSlugField(default='', editable=False, max_length=100, populate_from='category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_type_clean',
            field=autoslug.fields.AutoSlugField(default='', editable=False, max_length=100, populate_from='policy_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='government_entity_clean',
            field=autoslug.fields.AutoSlugField(default='', editable=False, max_length=100, populate_from='government_entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='name_clean',
            field=autoslug.fields.AutoSlugField(default='', editable=False, max_length=100, populate_from='name'),
            preserve_default=False,
        ),
    ]
