# Generated by Django 2.0.1 on 2018-05-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_permitdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitdata',
            name='in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
