# Generated by Django 2.0.1 on 2018-06-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_taxlotdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxlotdata',
            name='sale_date',
            field=models.CharField(max_length=6),
        ),
    ]
