# Generated by Django 2.0.1 on 2018-06-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180604_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxlotdata',
            old_name='orig_ogr_f',
            new_name='orig_ogc_f',
        ),
    ]
