# Generated by Django 2.0.1 on 2018-06-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180604_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxlotdata',
            old_name='percent_change_2011_2017',
            new_name='percent_change',
        ),
        migrations.RemoveField(
            model_name='taxlotdata',
            name='building_value_2011',
        ),
        migrations.RemoveField(
            model_name='taxlotdata',
            name='gis_acres',
        ),
        migrations.RemoveField(
            model_name='taxlotdata',
            name='juris_city',
        ),
        migrations.RemoveField(
            model_name='taxlotdata',
            name='land_value_2011',
        ),
        migrations.RemoveField(
            model_name='taxlotdata',
            name='state_class',
        ),
        migrations.RemoveField(
            model_name='taxlotdata',
            name='total_value_2011',
        ),
        migrations.AddField(
            model_name='taxlotdata',
            name='at_diff',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxlotdata',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxlotdata',
            name='owner_state',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
