# Generated by Django 2.0.1 on 2018-06-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_taxlotdata_area_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxlotdata',
            name='at_diff',
            field=models.IntegerField(null=True),
        ),
    ]
