# Generated by Django 2.0.1 on 2018-06-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180613_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxlotdata',
            name='year',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
